version: "3"

services:

  frontend:
    build:
      context: ./frontend
    container_name: appb_frontend
    restart: always


  nginx:
    image: nginx:alpine
    container_name: appb_nginx
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - frontend
